### ISSUE TITLE
Bug lors de la modification d'un nouvel utilisateur

### ISSUE THREAD

**Issue by pollux1er** [pollux1er/PerencoCanteenAdmin#1]
Après avoir ajouté un nouvel utilisateur, je suis allé dans la liste des utilisateurs, il m'a été impossible de l'ouvrir pour le modifier. Son iduser était manquant.

**Comment by FrankNBF** [comment]
C'est ok

**Comment by pollux1er** [comment]
Oui ca marche parfaitment maintenant.
