### ISSUE TITLE
Uniformiser la langue

### ISSUE THREAD

**Issue by pollux1er** [pollux1er/PerencoCanteenAdmin#3]
Lorsqu'on veut ajouter un utilisateur, le select du type de l'utilisateur fait référence à Organic au lieu de Organique.

**Comment by FrankNBF** [comment]
j'ai remplacé le texte de organic seulement lors de l'affichage, dans la base de données il reste toujours inchangé. J'ai aussi corrigé organic, visitor et contracted dans la liste des users, pour les afficher en français

**Comment by pollux1er** [comment]
Ok
